#!/usr/bin/env python
#.*. coding: utf-8 .*.

import os

letra=raw_input('Dime la letra: ')
directorio=raw_input('Dime el directorio: ')

if not os.access(directorio,0):
	print ('dir not exist')
	exit()

ficheros=os.listdir(directorio)

for f in ficheros:
	if f.count(letra)>0:
		print f 

