#!/usr/bin/env python
#.*. coding: utf-8 .*.

import os

directorio=raw_input('dime un directorio: ')

if not os.access(directorio,0):
	print ('dir not exist')
	exit()

ficheros=os.listdir(directorio)

for f in ficheros:
	if f[-3:] == '.sh':
		print f
