#!/usr/bin/env python
#.*. coding: utf-8 .*.

import os
import sys

if len(sys.argv) != 4:
	print 'Argumentos equivocados!'
	exit()

iniciales=sys.argv[1][0]+','+sys.argv[2][0]+','+sys.argv[3][0]
print "Tus iniciales maiuscolas son : "+iniciales.upper()
print "Tus iniciales minuscolas son : "+iniciales
