#!/usr/bin/env python
#.*. coding: utf-8 .*.

import os
import sys

if len(sys.argv) != 2:
	print 'error!'
	exit()

print "El primer argumento es el nombre del programa: " + sys.argv[0]
print "segundo argumento: " + sys.argv[1]
print "segundo argumento maiuscolo: " + sys.argv[1].upper()
